name: CI

on: [push]

env:
  DEPLOY_PATH: ./
  # В теории можно собрать не только Vue-приложение, так как принцип сборки мало где отличается
  BUILD_SCRIPT: npm run build
  BUILD_SCRIPT_OUTPUT: ./dist

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Делаем checkout текущей ветки
      - uses: actions/checkout@v2
      # Устанавливаем Node.JS для сборки приложения
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      # Записываем в переменные окружения имя текущей ветки
      # Чтобы избежать конфиликтов с URL, меняем точки на _, а слеши на минусы
      - name: Get branch name
        shell: bash
        run: echo `::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g' | sed 's/\./_/g')`
      # Устанавливаем зависимости для сборки
      - name: Install Dependencies
        run: npm i
      # Собираем приложение
      - name: Build Appliction
        run: $BUILD_SCRIPT
      # Доставляем собранное приложение на сервер
      - name: Deploy to Server
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: '${{ secrets.DEPLOY_SERVER_HOST }}'
          port: ${{ secrets.DEPLOY_SERVER_PORT }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
          localPath: ${{ env.BUILD_SCRIPT_OUTPUT }}
          remotePath: ${{ env.DEPLOY_PATH }}
      - name: Print Info
        run: echo `Deployed at https://${BRANCH_NAME}.app.example.ru/`
